// obs-config.h — minimal stub for building against OBS source headers in CI
// The real obs-config.h is generated by OBS's own cmake configure step.
// This stub satisfies the includes required by libobs headers without needing
// OBS's full cmake build environment.
#pragma once

#define LIBOBS_API_MAJOR_VER 30
#define LIBOBS_API_MINOR_VER 2
#define LIBOBS_API_PATCH_VER 2
#define LIBOBS_API_VER ((30 << 24) | (2 << 16) | 2)
#define OBS_VERSION "30.2.2"
#define OBS_VERSION_CANONICAL "30.2.2"

// Feature flags (conservative defaults — disable optional features)
#ifndef OBS_LEGACY_AVCAPT
#define OBS_LEGACY_AVCAPT
#endif
